Update CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -69,19 +69,19 @@ jobs:
       - run:
           name: Deploy API to Rancher
           command: |
+            export SERVER_TAG=$AWS_ECR_URL/threes/server
             eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
             cd server
-            SERVERV2_TAG=$(cat build/SERVERV2_TAG)
-            docker build -t $SERVERV2_TAG build
-            docker push $SERVERV2_TAG
+            docker build -t $SERVER_TAG build
+            docker push $SERVER_TAG
 
-            echo $RANCHER_CLI_JSON > cli2.json
-            RANCHER="docker run -v $(pwd)/cli2.json:/root/.rancher/cli2.json --rm bitbakery/rancher-cli-k8s rancher"
-            $RANCHER login $RANCHER_URL --token $RANCHER_TOKEN
-            $RANCHER ps
+            # echo $RANCHER_CLI_JSON > cli2.json
+            # RANCHER="docker run -v $(pwd)/cli2.json:/root/.rancher/cli2.json --rm bitbakery/rancher-cli-k8s rancher"
+            # $RANCHER login $RANCHER_URL --token $RANCHER_TOKEN
+            # $RANCHER ps
 
-            SERVER_UPDATED=$($RANCHER kubectl --namespace=threes set image deployment/server server=$SERVERV2_TAG)
-            (test -z "$SERVER_UPDATED" && $RANCHER kubectl --namespace=threes rollout restart deployment/server) || echo 0 # Override with 0 exit code.
+            # SERVER_UPDATED=$($RANCHER kubectl --namespace=threes set image deployment/server server=$SERVER_TAG)
+            # (test -z "$SERVER_UPDATED" && $RANCHER kubectl --namespace=threes rollout restart deployment/server) || echo 0 # Override with 0 exit code.
 
       - run:
           name: Deploy to S3
